name: ci-test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8-debian
        env:
          MYSQL_DATABASE: simple_bank
          MYSQL_USER: root
          MYSQL_PASSWORD: secret
          MYSQL_ROOT_PASSWORD: secret
        ports:
          - 3356:3306
        options: --health-cmd="mysqladmin ping" --h
    steps:
      - name: Check out code into Go module directory
      - uses: actions/checkout@v3

      - name: Run migration
        run: make mysql_migrateup
        
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        run: go build -v ./...

      - name: Test
        run: make test
